---
- hosts: all
  gather_facts: no
  become: true
  vars:
    wrkdir: /etc/sf

  tasks:
  # Create a directory and copy files
  - name: Create a working directory
    ansible.builtin.file:
      path: "{{ wrkdir }}"
      state: directory
      mode: "777"

  - name: Copy necessary files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "{{ wrkdir }}"
    loop:
      - html
      - Jenkinsfile

  # Install Docker
  - name: Install Docker dependencies
    ansible.builtin.apt:
      name: "{{ item }}"
      state: latest
      update_cache: true
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent

  - name: Add Docker GPG apt Key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    ansible.builtin.apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Start docker
    ansible.builtin.service:
      name: docker
      enabled: true
      state: started

  - name: Install git
    apt:
      name: git
      state: present
      update_cache: true
